### ISSUE TITLE
Revision, Clarity language check

### ISSUE THREAD

**Issue by PardusEidolon** [PardusEidolon/Halo-3-Editing-Kit-Cookbook#12]
# Revise the H3EK

This document is started out as a dumping ground for things that were discovered during the modding process when the tools were first released. To make the concepts and language clearer a revision may have to be put in order.

### Tasks
- [ ] Go through the process of the guides and update the workflow and language if not clear enough
- [ ] Fix typos throughout the document
- [ ] Revise chapters completely if you come to the conclusion that it is not clear enough
- [ ] Add information in the UV chapter
